export const REQUEST_CLASS_SCLASSE = "REQUEST_CLASS_SCLASSE";

export const REQUEST_CLASS = "REQUEST_CLASS";
export const REQUEST_CLASS_SUCCESS = "REQUEST_CLASS_SUCCESS";
export const REQUEST_CLASS_FAIL = "REQUEST_CLASS_FAIL";

export const ADD_CLASS = "ADD_CLASS";
export const ADD_CLASS_SUCCESS = "ADD_CLASS_SUCCESS";
export const ADD_CLASS_FAIL = "ADD_CLASS_FAIL";

export const EDITING_CLASS = "EDIT_CLASS";
export const EDIT_SAVING_CLASS = "EDIT_SAVING_CLASS";
export const EDIT_CLASS_SUCCESS = "EDIT_CLASS_SUCCESS";
export const EDIT_CLASS_FAIL = "EDIT_CLASS_FAIL";

export const BUNCH_DELETE_CLASS = "BUNCH_DELETE_CLASS";
export const DELETE_CLASS = "DELETE_CLASS";
export const DELETE_CLASS_SUCCESS = "DELETE_CLASS_SUCCESS";
export const DELETE_CLASS_FAIL = "DELETE_CLASS_FAIL";


export const GET_CLASS_REQUEST = "GET_CLASS_REQUEST";
export const GET_CLASS_SUCCESS = "GET_CLASS_SUCCESS";
export const CLASS_RESPONSE = "CLASS_RESPONSE";
export const GET_CLASS_FAIL = "GET_CLASS_FAIL";
export const CLASS_CATCHERROR = "CLASS_CATCHERROR";
export const CLASS_RESET = "CLASS_RESET";
export const GET_SELECTED_CLASS_SUCCESS = "GET_SELECTED_CLASS_SUCCESS"
export const EDIT_SELECTED_CLASS_SUCCESS = "EDIT_SELECTED_CLASS_SUCCESS"
export const DELETED_SELECTED_CLASS_SUCCESS = "DELETED_SELECTED_CLASS_SUCCESS"
// src/actions/GetClassAction.js