export const GET_EDITOR_REQUEST = "GET_EDITOR_REQUEST";
export const GET_EDITOR_SUCCESS = "GET_EDITOR_SUCCESS";
export const EDITOR_RESPONSE = "EDITOR_RESPONSE";
export const GET_EDITOR_FAIL = "GET_EDITOR_FAIL";
export const EDITOR_CATCHERROR = "EDITOR_CATCHERROR";
export const EDITOR_RESET = "EDITOR_RESET";
export const GET_SELECTED_EDITOR_SUCCESS = "GET_SELECTED_EDITOR_SUCCESS"
export const UPDATE_SELECTED_EDITOR_SUCCESS = "UPDATE_SELECTED_EDITOR_SUCCESS"
export const DELETED_SELECTED_EDITOR_SUCCESS = "DELETED_SELECTED_EDITOR_SUCCESS"
// src\actions\GetEditorAction.js
