export const REQUEST_EDITOR                    = "REQUEST_EDITOR";
export const REQUEST_EDITOR_TITLE_LIST_SUCCESS = "REQUEST_EDITOR_TITLE_LIST_SUCCESS";
export const REQUEST_EDITOR_TITLE_LIST_FAIL = "REQUEST_EDITOR_TITLE_LIST_FAIL";
export const REQUEST_EDITOR_BY_TITLE           = "REQUEST_EDITOR_BY_TITLE";
export const REQUEST_EDITOR_SUCCESS            = "REQUEST_EDITOR_SUCCESS";
export const REQUEST_EDITOR_FAIL               = "REQUEST_EDITOR_FAIL";

export const ADD_EDITOR         = "ADD_EDITOR";
export const ADD_EDITOR_SUCCESS = "ADD_EDITOR_SUCCESS";
export const ADD_EDITOR_FAIL    = "ADD_EDITOR_FAIL";

export const UPDATE_EDITOR         = "UPDATE_EDITOR";
export const UPDATE_EDITOR_SUCCESS = "UPDATE_EDITOR_SUCCESS";
export const UPDATE_EDITOR_FAIL    = "UPDATE_EDITOR_FAIL";

export const DELETE_EDITOR         = "DELETE_EDITOR";
export const DELETE_EDITOR_SUCCESS = "DELETE_EDITOR_SUCCESS";
export const DELETE_EDITOR_FAIL    = "DELETE_EDITOR_FAIL";
