export const SET_DEFAULT_FORM_VALUE = "SET_DEFAULT_FORM_VALUE";
export const RESET_FORM_VALUE = "RESET_FORM_VALUE";

export const SET_MAIN_TITLE = "SET_MAIN_TITLE";
export const SET_MAIN_CONTENT = "SET_MAIN_CONTENT";

export const SET_HEADER_TITLE = "SET_HEADER_TITLE";
export const SET_HEADER_DESCRIPTION = "SET_HEADER_DESCRIPTION";
export const SET_HEADER_KEYWORDS = "SET_HEADER_KEYWORDS";
export const SET_HEADER_MANUAL_URL = "SET_HEADER_MANUAL_URL";

export const SET_PUBLISH_INFO_HIDDEN = "SET_PUBLISH_INFO_HIDDEN";
export const SET_PUBLISH_INFO_IS_SCHEDULED = "SET_PUBLISH_INFO_IS_SCHEDULED";

export const SET_PROPERTY = "SET_PROPERTY";