export const SET_DEFAULT_FORM_VALUE = "SET_DEFAULT_FORM_VALUE";
export const RESET_FORM_VALUE = "RESET_FORM_VALUE";
export const SET_PROPERTY = "SET_PROPERTY";
export const CHECK_BEFORE_SUBMIT = "CHECK_BEFORE_SUBMIT";