export const REQUEST_TAG_STAGE = "REQUEST_TAG_STAGE";

export const REQUEST_TAG_PAGE = "REQUEST_TAG_PAGE";
export const SHOW_TAG_LIST_SORTING = "SHOW_TAG_LIST_SORTING";
export const SEARCH_TAG_LIST = "SEARCH_TAG_LIST";

export const REQUEST_TAG = "REQUEST_TAG";
export const REQUEST_TAG_SUCCESS = "REQUEST_TAG_SUCCESS";
export const REQUEST_TAG_FAIL = "REQUEST_TAG_FAIL";

export const ADD_TAG = "ADD_TAG";
export const ADD_TAG_SUCCESS = "ADD_TAG_SUCCESS";
export const ADD_TAG_FAIL = "ADD_TAG_FAIL";

export const EDITING_TAG = "EDITING_TAG";
export const EDIT_SAVING_TAG = "EDIT_SAVING_TAG";

export const UPDATE_TAG = "UPDATE_TAG";
export const UPDATE_TAG_SUCCESS = "UPDATE_TAG_SUCCESS";
export const UPDATE_TAG_FAIL = "UPDATE_TAG_FAIL";

export const BUNCH_DELETE_TAG = "BUNCH_DELETE_TAG";
export const DELETE_TAG = "DELETE_TAG";
export const DELETE_TAG_SUCCESS = "DELETE_TAG_SUCCESS";
export const DELETE_TAG_FAIL = "DELETE_TAG_FAIL";

export const GET_TAG_REQUEST = "GET_TAG_REQUEST";
export const GET_TAG_SUCCESS = "GET_TAG_SUCCESS";
export const TAG_RESPONSE = "TAG_RESPONSE";
export const GET_TAG_FAIL = "GET_TAG_FAIL";
export const TAG_CATCHERROR = "TAG_CATCHERROR";
export const TAG_RESET = "TAG_RESET";
export const GET_SELECTED_TAG_SUCCESS = "GET_SELECTED_TAG_SUCCESS"
export const UPDATE_SELECTED_TAG_SUCCESS = "UPDATE_SELECTED_TAG_SUCCESS"
export const DELETED_SELECTED_TAG_SUCCESS = "DELETED_SELECTED_TAG_SUCCESS"

export const REQUEST_POPULAR_TAG = "REQUEST_POPULAR_TAG";
export const REQUEST_POPULAR_TAG_SUCCESS = "REQUEST_POPULAR_TAG_SUCCESS";
export const REQUEST_POPULAR_TAG_FAIL = "REQUEST_POPULAR_TAG_FAIL";