export const GET_TAG_REQUEST = "GET_TAG_REQUEST";
export const GET_TAG_SUCCESS = "GET_TAG_SUCCESS";
export const TAG_RESPONSE = "TAG_RESPONSE";
export const GET_TAG_FAIL = "GET_TAG_FAIL";
export const TAG_CATCHERROR = "TAG_CATCHERROR";
export const TAG_RESET = "TAG_RESET";
export const GET_SELECTED_TAG_SUCCESS = "GET_SELECTED_TAG_SUCCESS"
export const UPDATE_SELECTED_TAG_SUCCESS = "UPDATE_SELECTED_TAG_SUCCESS"
export const DELETED_SELECTED_TAG_SUCCESS = "DELETED_SELECTED_TAG_SUCCESS"
// src/actions/GetTagsAction.js